use serde::{Deserialize,Serialize};
use std::{fs,path::{Path,PathBuf},process::{Command,Stdio}};
#[derive(Serialize)] struct HardwareInfo{gpu:String,vram_mb:Option<u64>,nvidia:bool,recommended_profile:String}
#[derive(Serialize,Deserialize,Clone)] struct ModelSpec{id:String,name:String,kind:String,size_gb:f32,min_vram_gb:u32,url:String,filename:String,folder:String,license:String,sha256:Option<String>,recommended_profiles:Vec<String>}
#[derive(Serialize)] struct ModelState{spec:ModelSpec,installed:bool,partial:bool,recommended:bool}
#[derive(Serialize)] struct DiskInfo{free_gb:f64,engine_path:String}
fn root()->PathBuf{std::env::var("LOCALAPPDATA").map(PathBuf::from).unwrap_or_else(|_|PathBuf::from(".")).join("NavagartAI").join("engine")}
fn comfy()->PathBuf{root().join("ComfyUI")} fn runtime()->PathBuf{root().join("python")}
fn catalog()->Vec<ModelSpec>{vec![
ModelSpec{id:"sdxl-base".into(),name:"SDXL Base 1.0".into(),kind:"image".into(),size_gb:6.9,min_vram_gb:8,url:"https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors".into(),filename:"sd_xl_base_1.0.safetensors".into(),folder:"checkpoints".into(),license:"Stability AI / CreativeML Open RAIL++-M. Review model card before use.".into(),sha256:None,recommended_profiles:vec!["image-only".into(),"wan-low-vram".into()]},
ModelSpec{id:"flux1-schnell".into(),name:"FLUX.1 Schnell".into(),kind:"image".into(),size_gb:23.8,min_vram_gb:16,url:"https://huggingface.co/black-forest-labs/FLUX.1-schnell/resolve/main/flux1-schnell.safetensors".into(),filename:"flux1-schnell.safetensors".into(),folder:"unet".into(),license:"Apache-2.0 for FLUX.1-schnell weights; review model card and dependencies.".into(),sha256:None,recommended_profiles:vec!["wan-balanced".into(),"wan-quality".into()]}
]}
fn hardware()->HardwareInfo{if let Ok(o)=Command::new("nvidia-smi").args(["--query-gpu=name,memory.total","--format=csv,noheader,nounits"]).output(){if o.status.success(){let t=String::from_utf8_lossy(&o.stdout);let l=t.lines().next().unwrap_or("");let mut p=l.rsplitn(2,',');let v=p.next().and_then(|x|x.trim().parse::<u64>().ok());let g=p.next().unwrap_or("NVIDIA GPU").trim().to_string();let profile=match v.unwrap_or(0){0..=8191=>"image-only",8192..=15999=>"wan-low-vram",16000..=23999=>"wan-balanced",_=>"wan-quality"}.into();return HardwareInfo{gpu:g,vram_mb:v,nvidia:true,recommended_profile:profile}}}HardwareInfo{gpu:"No NVIDIA GPU detected".into(),vram_mb:None,nvidia:false,recommended_profile:"image-only".into()}}
#[tauri::command]fn detect_hardware()->HardwareInfo{hardware()}
#[tauri::command]fn engine_status()->String{if comfy().exists(){"installed".into()}else{"not-installed".into()}}
#[tauri::command]fn disk_info()->DiskInfo{let p=root();let escaped=p.to_string_lossy().replace("'","''");let ps=format!("$p='{}';$d=(Get-Item ($p.Substring(0,3))).PSDrive;[math]::Round($d.Free/1GB,2)",escaped);let free=Command::new("powershell").args(["-NoProfile","-Command",&ps]).output().ok().and_then(|o|String::from_utf8(o.stdout).ok()).and_then(|s|s.trim().replace(',','.').parse::<f64>().ok()).unwrap_or(0.0);DiskInfo{free_gb:free,engine_path:p.to_string_lossy().to_string()}}
fn download_resume(url:&str,dest:&Path)->Result<(),String>{if let Some(p)=dest.parent(){fs::create_dir_all(p).map_err(|e|e.to_string())?}let part=dest.with_extension(format!("{}part",dest.extension().map(|x|format!("{}.",x.to_string_lossy())).unwrap_or_default()));let ps=format!("$ProgressPreference='SilentlyContinue';$u='{}';$p='{}';$d='{}';$start=if(Test-Path $p){{(Get-Item $p).Length}}else{{0}};$h=@{{}};if($start -gt 0){{$h['Range']='bytes='+$start+'-'}};$r=Invoke-WebRequest -UseBasicParsing -Uri $u -Headers $h;if($start -gt 0){{[IO.File]::WriteAllBytes($p,([IO.File]::ReadAllBytes($p)+$r.Content))}}else{{[IO.File]::WriteAllBytes($p,$r.Content)}};Move-Item -Force $p $d",url.replace("'","''"),part.to_string_lossy().replace("'","''"),dest.to_string_lossy().replace("'","''"));let s=Command::new("powershell").args(["-NoProfile","-Command",&ps]).status().map_err(|e|e.to_string())?;if s.success(){Ok(())}else{Err("Falló la descarga; el archivo parcial se conserva para reanudar".into())}}
fn sha256(path:&Path)->Result<String,String>{let o=Command::new("powershell").args(["-NoProfile","-Command",&format!("(Get-FileHash -Algorithm SHA256 '{}').Hash.ToLower()",path.to_string_lossy().replace("'","''"))]).output().map_err(|e|e.to_string())?;Ok(String::from_utf8_lossy(&o.stdout).trim().to_string())}
fn bootstrap_python()->Result<PathBuf,String>{let r=runtime();let py=r.join("python.exe");if py.exists(){return Ok(py)}fs::create_dir_all(&r).map_err(|e|e.to_string())?;let zip=root().join("python.zip");download_resume("https://www.python.org/ftp/python/3.13.15/python-3.13.15-embed-amd64.zip",&zip)?;let ps=format!("Expand-Archive -Force '{}' '{}'",zip.to_string_lossy(),r.to_string_lossy());if !Command::new("powershell").args(["-NoProfile","-Command",&ps]).status().map_err(|e|e.to_string())?.success(){return Err("No se pudo extraer Python".into())}let pth=r.join("python313._pth");if pth.exists(){let txt=fs::read_to_string(&pth).map_err(|e|e.to_string())?.replace("#import site","import site");fs::write(&pth,txt).map_err(|e|e.to_string())?}let gp=root().join("get-pip.py");download_resume("https://bootstrap.pypa.io/get-pip.py",&gp)?;if !Command::new(&py).arg(&gp).status().map_err(|e|e.to_string())?.success(){return Err("No se pudo instalar pip".into())}Ok(py)}
#[tauri::command]fn install_ai_engine()->Result<String,String>{fs::create_dir_all(root()).map_err(|e|e.to_string())?;let py=bootstrap_python()?;if !comfy().exists(){let zip=root().join("comfyui.zip");download_resume("https://github.com/Comfy-Org/ComfyUI/archive/refs/heads/master.zip",&zip)?;let tmp=root().join("comfy-tmp");let ps=format!("Expand-Archive -Force '{}' '{}'",zip.to_string_lossy(),tmp.to_string_lossy());if !Command::new("powershell").args(["-NoProfile","-Command",&ps]).status().map_err(|e|e.to_string())?.success(){return Err("No se pudo extraer ComfyUI".into())}fs::rename(tmp.join("ComfyUI-master"),comfy()).map_err(|e|e.to_string())?;let _=fs::remove_dir_all(tmp)}let req=comfy().join("requirements.txt");if !Command::new(&py).args(["-m","pip","install","-r",req.to_string_lossy().as_ref()]).status().map_err(|e|e.to_string())?.success(){return Err("Falló la instalación de dependencias".into())}Ok(root().to_string_lossy().to_string())}
#[tauri::command]fn start_ai_engine()->Result<String,String>{let py=runtime().join("python.exe");if !py.exists(){return Err("Instala primero el motor IA".into())}Command::new(py).current_dir(comfy()).args(["main.py","--listen","127.0.0.1","--port","8188"]).stdout(Stdio::null()).stderr(Stdio::null()).spawn().map_err(|e|e.to_string())?;Ok("started".into())}
#[tauri::command]fn list_models()->Vec<ModelState>{let profile=hardware().recommended_profile;catalog().into_iter().map(|s|{let dest=comfy().join("models").join(&s.folder).join(&s.filename);let installed=dest.exists();let partial=dest.with_extension(format!("{}part",dest.extension().map(|x|format!("{}.",x.to_string_lossy())).unwrap_or_default())).exists();let recommended=s.recommended_profiles.contains(&profile);ModelState{spec:s,installed,partial,recommended}}).collect()}
#[tauri::command]fn install_model(id:String,accepted_license:bool)->Result<String,String>{if !accepted_license{return Err("Debes aceptar/revisar la licencia del modelo".into())}let s=catalog().into_iter().find(|m|m.id==id).ok_or("Modelo desconocido")?;let free=disk_info().free_gb;if free<(s.size_gb as f64+2.0){return Err(format!("Espacio insuficiente: necesitas aproximadamente {:.1} GB libres",s.size_gb+2.0))}let dest=comfy().join("models").join(&s.folder).join(&s.filename);download_resume(&s.url,&dest)?;if let Some(expected)=s.sha256{let got=sha256(&dest)?;if got!=expected.to_lowercase(){let _=fs::remove_file(&dest);return Err("SHA-256 incorrecto; se eliminó la descarga".into())}}Ok(dest.to_string_lossy().to_string())}
#[tauri::command]fn verify_model(id:String)->Result<String,String>{let s=catalog().into_iter().find(|m|m.id==id).ok_or("Modelo desconocido")?;let dest=comfy().join("models").join(&s.folder).join(&s.filename);if !dest.exists(){return Err("Modelo no instalado".into())}sha256(&dest)}
#[tauri::command]fn remove_model(id:String)->Result<String,String>{let s=catalog().into_iter().find(|m|m.id==id).ok_or("Modelo desconocido")?;let dest=comfy().join("models").join(&s.folder).join(&s.filename);if dest.exists(){fs::remove_file(dest).map_err(|e|e.to_string())?}Ok("removed".into())}
#[cfg_attr(mobile,tauri::mobile_entry_point)]pub fn run(){tauri::Builder::default().invoke_handler(tauri::generate_handler![engine_status,detect_hardware,disk_info,install_ai_engine,start_ai_engine,list_models,install_model,verify_model,remove_model]).run(tauri::generate_context!()).expect("error while running Navagart AI Studio");}
