import { useEffect, useMemo, useState } from 'react';
import { Aperture, Clapperboard, FolderOpen, GalleryVerticalEnd, Image, Layers3, Play, Settings, Sparkles, Video } from 'lucide-react';
import { dimensionsForRatio, getComfyStatus, queueWorkflow } from './lib/comfyui';
import { buildWorkflow } from './lib/workflows';

type Mode = 'Text → Image' | 'Image → Image' | 'Text → Video' | 'Image → Video';
const modes: { label: Mode; icon: typeof Image }[] = [{label:'Text → Image',icon:Image},{label:'Image → Image',icon:Layers3},{label:'Text → Video',icon:Video},{label:'Image → Video',icon:Clapperboard}];
const cameras=['Static','Dolly In','Dolly Out','Orbit Left','Orbit Right','Crane Up','Handheld','FPV'];

export default function App(){
 const[mode,setMode]=useState<Mode>('Text → Image'); const[prompt,setPrompt]=useState(''); const[negativePrompt,setNegativePrompt]=useState(''); const[ratio,setRatio]=useState('16:9'); const[camera,setCamera]=useState('Dolly In'); const[queued,setQueued]=useState(0); const[model,setModel]=useState('sd_xl_base_1.0.safetensors'); const[seed,setSeed]=useState(''); const[engine,setEngine]=useState<'checking'|'ready'|'offline'>('checking'); const[status,setStatus]=useState('Waiting'); const[lastJob,setLastJob]=useState('');
 const mediaKind=useMemo(()=>mode.includes('Video')?'vídeo':'imagen',[mode]);
 useEffect(()=>{getComfyStatus().then(()=>setEngine('ready')).catch(()=>setEngine('offline'))},[]);
 async function generate(){try{setStatus('Sending…');const dims=dimensionsForRatio(ratio);const workflow=buildWorkflow({mode,prompt,negativePrompt,model,...dims,seed:seed?Number(seed):undefined,camera});const result=await queueWorkflow(workflow);setLastJob(result.prompt_id);setQueued(q=>q+1);setStatus('Queued in ComfyUI')}catch(error){setStatus(error instanceof Error?error.message:'Generation error')}}
 return <div className="shell"><aside className="sidebar"><div className="brand"><div className="brandMark"><Aperture size={22}/></div><div><strong>NAVAGART</strong><span>AI STUDIO</span></div></div><nav><button className="nav active"><Sparkles size={18}/> Create</button><button className="nav"><GalleryVerticalEnd size={18}/> Generations</button><button className="nav"><FolderOpen size={18}/> Projects</button><button className="nav"><Layers3 size={18}/> Assets</button></nav><div className="sidebarBottom"><button className="nav"><Settings size={18}/> Settings</button><div className="local"><span className={`dot ${engine==='offline'?'offline':''}`}/> ComfyUI: {engine}</div></div></aside><main><header><div><span className="eyebrow">CREATE</span><h1>Turn ideas into motion.</h1><p>Genera imágenes y vídeo desde una sola estación de trabajo.</p></div><button className="queue">Queue <b>{queued}</b></button></header><section className="modebar">{modes.map(({label,icon:Icon})=><button key={label} onClick={()=>setMode(label)} className={mode===label?'selected':''}><Icon size={17}/>{label}</button>)}</section><div className="workspace"><section className="composer card"><div className="cardTitle"><span>Generation</span><span className="badge">V0.2 LOCAL</span></div><label>Prompt</label><textarea value={prompt} onChange={e=>setPrompt(e.target.value)} placeholder={`Describe el ${mediaKind} que quieres crear...`}/><label>Negative prompt</label><input value={negativePrompt} onChange={e=>setNegativePrompt(e.target.value)} placeholder="blurry, distorted, watermark…"/><div className="fieldGrid"><div><label>Provider</label><select><option>Local / ComfyUI</option></select></div><div><label>Checkpoint</label><input value={model} onChange={e=>setModel(e.target.value)} placeholder="modelo.safetensors"/></div><div><label>Aspect ratio</label><select value={ratio} onChange={e=>setRatio(e.target.value)}><option>16:9</option><option>9:16</option><option>1:1</option></select></div><div><label>Seed</label><input value={seed} onChange={e=>setSeed(e.target.value)} placeholder="Random"/></div></div>{mode.includes('Video')&&<><label>Camera motion</label><div className="chips">{cameras.map(c=><button key={c} onClick={()=>setCamera(c)} className={camera===c?'activeChip':''}>{c}</button>)}</div></>}<button className="generate" onClick={generate} disabled={!prompt.trim()||engine!=='ready'}><Sparkles size={18}/> Generate {mediaKind}</button></section><section className="preview card"><div className="previewTop"><span>Engine / Job</span><span>{ratio}</span></div><div className={`canvas ratio-${ratio.replace(':','')}`}><div className="empty"><Play size={30}/><strong>{engine==='ready'?'ComfyUI connected':'Start ComfyUI on port 8188'}</strong><span>{status}</span>{lastJob&&<span>Job: {lastJob.slice(0,12)}…</span>}</div></div><div className="status"><span><span className={`dot ${engine==='offline'?'offline':''}`}/> Local engine</span><b>{status}</b></div></section></div></main></div>;
}
